### ISSUE TITLE
gcd stuck when only one vCPU

### ISSUE THREAD

**Issue by FrankReh** [kprotty/uasync#2]
It appears when the benchmarks are run on a single vCPU, the RandomSequence::new call never returns because it is passed a value of 1, and as a result gcd is called with values 0 and 1, resulting in an infinite loop.

Otherwise, am enjoying looking through this very tight package.

**Comment by kprotty** [comment]
RIP, sounds like an easy fix though. Thanks for pointing it out.

**Comment by FrankReh** [comment]
If you are using rust 1.59 or 1.60, you'll run into the change made to unreachable breaking the build. Found this which goes to explaining why a breaking change was considered acceptable to the team. The fix was easy but the breakage surprised me, being new to rust, so I looked for the discussion behind it.  https://github.com/rust-lang/rust/issues/92137#issuecomment-1057906690

Just reading more, for educational purposes, the 2021 Edition came with these release notes, https://doc.rust-lang.org/edition-guide/rust-2021/panic-macro-consistency.html, explaining why some compiler macros now require a string literal as the first arg. Seems they forgot to include unreachable for 1.56 so they fixed it by 1.59. Sorry for this noise, you may be finding all this much faster than I did. Wanted to say again, your rust packages are great to read through for a newcomer.
